### ISSUE TITLE
Encoding Rules Not Accurate?

### ISSUE THREAD

**Issue by linuxwolf** [bmeck/I-D#12]
The charset and encoding instructions that carry over from [RFC 4329](https://datatracker.ietf.org/doc/rfc4329) may not be correct.

At least for HTML-based agents, the following is relevant:
* https://html.spec.whatwg.org/multipage/scripting.html#prepare-a-script (step 21)
* https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-script (step 6,7)
* https://encoding.spec.whatwg.org/#decode (step 4)

Reconciling the above rules with the instructions from RFC 4329 may be needed.

**Comment by bmeck** [comment]
matching https://github.com/bmeck/I-D/issues/2#issuecomment-322694349 I have made encoding host dependent due to differences in BOM, charset, and removal of interpreter directives.
