### ISSUE TITLE
Mistype: «appliaction/ecmascript» instead of «application/ecmascript»

### ISSUE THREAD

**Issue by ChALkeR** [bmeck/I-D#15]
From #kde-devel:

> ‎[17:50] ‎<‎tosky‎>‎ chalker_: that's really new - and there is a typo: "4.1  appliaction/ecmascript" instead of application/ecmascript
> ‎[17:50] ‎<‎tosky‎>‎ not sure how to report it (if you know please do :)

That is currently present in https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs

It looks to be present in several places here.

Full search: https://github.com/bmeck/I-D/search?q=appliaction&type=Code

**Comment by bmeck** [comment]
@ChALkeR , fixed updating IETF site had an error and I have emailed them about it.

**Comment by ChALkeR** [comment]
Thanks!

**Comment by bmeck** [comment]
published: https://tools.ietf.org/html/draft-ietf-dispatch-javascript-mjs-01
